name: Build and Release Blender Addon

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Print working directory
        run: pwd

      - name: List all files and folders
        run: ls -R

      - name: Get tag name (version)
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "Extracted version: ${GITHUB_REF##*/}"

      - name: Show version env
        run: echo "Using VERSION=$VERSION"

      - name: Set up zip structure
        run: |
          mkdir -p build/codewalker_sollumz_bridge
          shopt -s extglob
          cp -r !(build|.git|.github) build/codewalker_sollumz_bridge
          cd build
          zip -r codewalker_sollumz_bridge_${VERSION}.zip codewalker_sollumz_bridge

      - name: List build folder
        run: ls -l build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/codewalker_sollumz_bridge_${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
